# Generated by Django 5.2.3 on 2025-06-17 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=35, verbose_name='тема письма')),
                ('content', models.TextField(verbose_name='содержание письма')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
                'permissions': [('can_view_mailing', 'Просмотр рассылок'), ('can_delete_mailing', 'Отключение рассылок')],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_mailing', models.DateTimeField(blank=True, null=True, verbose_name='первая рассылка')),
                ('frequency', models.CharField(choices=[('ON', 'Один раз'), ('DY', 'Раз в день'), ('WE', 'Раз в неделю'), ('MN', 'Раз в месяц')], default='DY', max_length=2, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('CR', 'Создана'), ('RN', 'Запущена'), ('FS', 'Завершена'), ('FL', 'Ошибка')], default='CR', max_length=2, verbose_name='Статус')),
                ('next_mailing', models.DateTimeField(blank=True, null=True, verbose_name='Следующая рассылка')),
                ('is_immediate', models.BooleanField(default=False, verbose_name='Немедленная отправка')),
                ('last_try', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка')),
                ('clients', models.ManyToManyField(to='clients.client', verbose_name='Клиенты')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='mailing.message', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'permissions': [('can_view_mailing', 'Просмотр рассылок'), ('can_delete_mailing', 'Отключение рассылок')],
            },
        ),
        migrations.CreateModel(
            name='MailingTrying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing', models.DateTimeField(verbose_name='последняя рассылка')),
                ('status_trying', models.CharField(choices=[('SC', 'Успешно'), ('FL', 'Неуспешно')], max_length=30, verbose_name='статус попытки')),
                ('server_response', models.CharField(max_length=1000)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытки рассылок',
            },
        ),
    ]
